# SPDX-License-Identifier: Apache-2.0
"""Literal pre-R80 fixtures for the shared operator-test matrix.

The values in this module are reconstructed from the duplicated literals that
were deleted when the R80 catalog migration landed.  Keep this module
independent from ``operator_cases``: the matrix gate must fail if the catalog
and every adapter co-drift together.
"""

from __future__ import annotations


OPERATOR_ORDER = (
    "sw",
    "sw_affine",
    "sv_linear",
    "sv_affine",
    "nw",
    "nw_affine",
    "dtw",
    "lcs",
    "lev",
    "osa",
    "damerau",
    "mas",
    "cky",
    "eisner",
)

_LINEAR_PROFILES = (
    ("contract", ((2, 4, 5),)),
    ("validation", ((1, 3, 3),)),
    ("func", ((2, 3, 3),)),
    ("compile", ((1, 4, 4),)),
    ("masking", ((1, 4, 4),)),
    ("mask_kwarg", ((1, 4, 4),)),
    ("invariance", ((1, 5, 5),)),
    ("autocast", ((1, 4, 4),)),
)


def _case(
    *,
    name,
    input_names,
    profiles,
    parameters,
    structural_defaults,
    vjp_fields,
    orientation,
    nn_class,
    operator_module,
    operator_name,
    nonnegative,
    off_optimal_index,
    padded_index,
    invariance_index,
):
    return {
        "name": name,
        "input_names": input_names,
        "profiles": profiles,
        "parameters": parameters,
        "structural_defaults": structural_defaults,
        "vjp_fields": vjp_fields,
        "orientation": orientation,
        "nn_class": nn_class,
        "operator_module": operator_module,
        "operator_name": operator_name,
        "nonnegative": nonnegative,
        "off_optimal_index": off_optimal_index,
        "padded_index": padded_index,
        "invariance_index": invariance_index,
    }


# Each parameter is (public name, contract default, matrix value, mask value,
# raw-vmap argument name).  Do not derive these tuples from the catalog.
EXPECTED_CASES = (
    _case(
        name="sw",
        input_names=("pair_scores",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("gap_score", 0.0, -0.7, -0.7, "gap"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None),),
        vjp_fields=("gap_score", "temperature"),
        orientation="score-native",
        nn_class="SmithWaterman",
        operator_module="orihime.sw",
        operator_name="_sw_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="sw_affine",
        input_names=("pair_scores",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("gap_open_score", 0.0, -1.0, -1.0, "gap_open"),
            ("gap_extend_score", 0.0, -0.3, -0.3, "gap_ext"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None),),
        vjp_fields=("gap_open_score", "gap_extend_score", "temperature"),
        orientation="score-native",
        nn_class="SmithWatermanAffine",
        operator_module="orihime.sw",
        operator_name="_sw_affine_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="sv_linear",
        input_names=("pair_scores",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("gap_score", 0.0, -0.7, -0.7, "gap"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None),),
        vjp_fields=("gap_score", "temperature"),
        orientation="score-native",
        nn_class="SaigoVertLinear",
        operator_module="orihime.sv",
        operator_name="_sv_linear_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="sv_affine",
        input_names=("pair_scores",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("gap_open_score", 0.0, -1.0, -1.0, "gap_open"),
            ("gap_extend_score", 0.0, -0.3, -0.3, "gap_ext"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None),),
        vjp_fields=("gap_open_score", "gap_extend_score", "temperature"),
        orientation="score-native",
        nn_class="SaigoVertAffine",
        operator_module="orihime.sv",
        operator_name="_sv_affine_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="nw",
        input_names=("pair_scores",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("gap_score", 0.0, -0.7, -0.7, "gap"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None),),
        vjp_fields=("gap_score", "temperature"),
        orientation="score-native",
        nn_class="NeedlemanWunsch",
        operator_module="orihime.nw",
        operator_name="_nw_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="nw_affine",
        input_names=("pair_scores",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("gap_open_score", 0.0, -1.0, -1.0, "gap_open"),
            ("gap_extend_score", 0.0, -0.3, -0.3, "gap_ext"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None),),
        vjp_fields=("gap_open_score", "gap_extend_score", "temperature"),
        orientation="score-native",
        nn_class="NeedlemanWunschAffine",
        operator_module="orihime.nw",
        operator_name="_nw_affine_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="dtw",
        input_names=("costs",),
        profiles=_LINEAR_PROFILES,
        parameters=(("temperature", 1.0, 0.9, 1.0, "temp"),),
        structural_defaults=(("lengths", None), ("bandwidth", None)),
        vjp_fields=("temperature",),
        orientation="cost-native",
        nn_class="DynamicTimeWarping",
        operator_module="orihime.dtw",
        operator_name="_dtw_operator",
        nonnegative=True,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="lcs",
        input_names=("match_scores",),
        profiles=_LINEAR_PROFILES,
        parameters=(("temperature", 1.0, 0.9, 1.0, "temp"),),
        structural_defaults=(("lengths", None),),
        vjp_fields=("temperature",),
        orientation="score-native",
        nn_class="LongestCommonSubsequence",
        operator_module="orihime.lcs",
        operator_name="_lcs_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="lev",
        input_names=("substitution_costs",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("insertion_cost", 1.0, 0.8, 0.8, "ins_cost"),
            ("deletion_cost", 1.0, 1.1, 1.1, "del_cost"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None),),
        vjp_fields=("insertion_cost", "deletion_cost", "temperature"),
        orientation="cost-native",
        nn_class="Levenshtein",
        operator_module="orihime.edit_distance",
        operator_name="_lev_operator",
        nonnegative=True,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="osa",
        input_names=("substitution_costs",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("insertion_cost", 1.0, 0.8, 0.8, "ins_cost"),
            ("deletion_cost", 1.0, 1.1, 1.1, "del_cost"),
            ("transposition_cost", 1.0, 0.7, 0.7, "trans_cost"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None), ("allowed_transpositions", None)),
        vjp_fields=(
            "insertion_cost",
            "deletion_cost",
            "transposition_cost",
            "temperature",
        ),
        orientation="cost-native",
        nn_class="OptimalStringAlignment",
        operator_module="orihime.osa",
        operator_name="_osa_operator",
        nonnegative=True,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="damerau",
        input_names=("substitution_costs",),
        profiles=_LINEAR_PROFILES,
        parameters=(
            ("insertion_cost", 1.0, 0.8, 0.8, "ins_cost"),
            ("deletion_cost", 1.0, 1.1, 1.1, "del_cost"),
            ("transposition_cost", 1.0, 0.7, 0.7, "trans_cost"),
            ("temperature", 1.0, 0.9, 1.0, "temp"),
        ),
        structural_defaults=(("lengths", None), ("transposition_sources", None)),
        vjp_fields=(
            "insertion_cost",
            "deletion_cost",
            "transposition_cost",
            "temperature",
        ),
        orientation="cost-native",
        nn_class="DamerauLevenshtein",
        operator_module="orihime.damerau",
        operator_name="_damerau_operator",
        nonnegative=True,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 2, 2),
    ),
    _case(
        name="mas",
        input_names=("scores",),
        profiles=(
            ("contract", ((2, 5, 3),)),
            ("validation", ((1, 4, 3),)),
            ("func", ((2, 4, 3),)),
            ("compile", ((1, 5, 3),)),
            ("masking", ((1, 5, 4),)),
            ("mask_kwarg", ((1, 5, 3),)),
            ("invariance", ((1, 5, 3),)),
            ("autocast", ((1, 5, 3),)),
        ),
        parameters=(("temperature", 1.0, 0.9, 1.0, "temp"),),
        structural_defaults=(("lengths", None),),
        vjp_fields=("temperature",),
        orientation="score-native",
        nn_class="MonotonicAlignmentSearch",
        operator_module="orihime.mas",
        operator_name="_mas_operator",
        nonnegative=False,
        off_optimal_index=(0, 1, 0),
        padded_index=(0, 4, 0),
        invariance_index=(0, 2, 1),
    ),
    _case(
        name="cky",
        input_names=("merge_scores", "leaf_scores"),
        profiles=(
            ("contract", ((2, 4, 4, 4), (2, 4))),
            ("validation", ((1, 3, 3, 3), (1, 3))),
            ("func", ((2, 3, 3, 3), (2, 3))),
            ("compile", ((1, 4, 4, 4), (1, 4))),
            ("masking", ((1, 4, 4, 4), (1, 4))),
            ("mask_kwarg", ((1, 4, 4, 4), (1, 4))),
            ("invariance", ((1, 4, 4, 4), (1, 4))),
            ("autocast", ((1, 4, 4, 4), (1, 4))),
        ),
        parameters=(("temperature", 1.0, 0.9, 1.0, "temp"),),
        structural_defaults=(),
        vjp_fields=("leaf_scores", "temperature"),
        orientation="score-native",
        nn_class="CKY",
        operator_module="orihime.cky",
        operator_name="_cky_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 1, 3),
        padded_index=(0, 1, 2, 3),
        invariance_index=(0, 0, 1, 3),
    ),
    _case(
        name="eisner",
        input_names=("arc_scores",),
        profiles=(
            ("contract", ((2, 4, 4),)),
            ("validation", ((1, 3, 3),)),
            ("func", ((2, 3, 3),)),
            ("compile", ((1, 4, 4),)),
            ("masking", ((1, 4, 4),)),
            ("mask_kwarg", ((1, 4, 4),)),
            ("invariance", ((1, 5, 5),)),
            ("autocast", ((1, 4, 4),)),
        ),
        parameters=(("temperature", 1.0, 0.9, 1.0, "temp"),),
        structural_defaults=(("lengths", None),),
        vjp_fields=("temperature",),
        orientation="score-native",
        nn_class="Eisner",
        operator_module="orihime.eisner",
        operator_name="_eisner_operator",
        nonnegative=False,
        off_optimal_index=(0, 0, 2),
        padded_index=(0, 3, 0),
        invariance_index=(0, 0, 2),
    ),
)

EXPECTED_AUTOCAST_DTYPE_IDS = ("fp16", "bf16")
